name: opex

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python-version }}"
    # Begin caching
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # End caching
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pylint opex test
    - name: Test with unittest
      run: |
        python -m unittest

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # Begin caching
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # End caching
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with with coverage
      run: |
        coverage run --branch -m unittest
        coverage xml
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage.xml
        path: coverage
    - name: cobertura-report
      uses: 5monkeys/cobertura-action@v7
      with:
        path: coverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        show_line: true
        show_branch: true
        show_missing: true
        minimum_coverage: 50
