name: opex

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
        python-version: [ 3.x ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pylint opex test
    - name: Run unittest
      run: |
        python -m unittest

  run-tests-with-coverage:
    env:
      minimum-coverage: 40

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.x ]

    runs-on: 
      ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pylint opex test
    - name: Run unittest with coverage
      run: |
        coverage run --branch -m unittest
        coverage xml
    - name: cobertura-coverage-report
      uses: 5monkeys/cobertura-action@v7
      with:
        path: coverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        show_line: true
        show_branch: true
        show_missing: true
        minimum_coverage: ${{ env.minimum-coverage }}
    - name: cobertura-clover-transform
      # Convert from cobertura to clover for clover-coverage-check
      run: |
        pip install cobertura-clover-transform
        cobertura-clover-transform coverage.xml --output clover-cov.xml
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: |
          coverage.xml
          clover-cov.xml
    - name: clover-coverage-check
      uses: johanvanhelden/gha-clover-test-coverage-check@v1
      with:
        percentage: ${{ env.minimum-coverage }}
        filename: clover-cov.xml
